language: python

python:
  - 2.6
  - 2.7
  - pypy

install:
  - pip install --use-mirrors coveralls
  - pip install --use-mirrors nose

script: coverage run --source=menu `which django-admin.py` test --settings=menu.test_settings menu

after_success:
  coveralls
