language: python
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

env:
  - DJANGO=Django==1.6
  - DJANGO=Django==1.7
  - DJANGO=Django==1.8

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=Django==1.7

    - python: 2.6
      env: DJANGO=Django==1.8

install:
  - pip install -q -e .
  - pip install -q $DJANGO
  - pip install -q codecov
  - pip install -q nose

script: coverage run --source=menu `which django-admin.py` test --settings=menu.test_settings menu

after_success:
  - codecov
